### ISSUE TITLE
can't set up the Firebase Configuration

### ISSUE THREAD

**Issue by sgsevier** [hritikaggarwal2/husky-buddy#27]
Hi guys! Awesome project so far! I'm trying to setup the firebase connection, and I copied over configuration over into the new Firebase.js file, but when I navigated to the link (https://console.firebase.google.com/u/0/project/study-buddy-uw/settings/general/web:NDRlNDQzNTQtNzY4NS00MmYwLWI1NmUtOGFjMjdiNmM1YzQz)  iIgot the error message below saying I don't have access. I tried my gmail, uw, and cs email to try and troubleshoot it but I get the same message. Should I be getting the config information a different way?

<img width="978" alt="Screen Shot 2021-05-23 at 4 46 52 PM" src="https://user-images.githubusercontent.com/36639758/119280588-eabc1900-bbe6-11eb-8001-2a98b0888b32.png">

<img width="1287" alt="Screen Shot 2021-05-23 at 4 50 13 PM" src="https://user-images.githubusercontent.com/36639758/119280602-f3acea80-bbe6-11eb-964b-94eac664e303.png">

**Comment by ilyasrepo** [comment]
This seems like an issue on our end, please ping me on slack, and I'll get the info to you

**Comment by ilyasrepo** [comment]
Issue resolved on slack
