### ISSUE TITLE
Permissions wall hit while following directions

### ISSUE THREAD

**Issue by nlstrait** [hritikaggarwal2/husky-buddy#31]
[This particular instruction](https://github.com/hritikaggarwal2/husky-buddy/blob/main/web/README.md#using-project-config-file) results in this dead-end:

<img width="736" alt="Screen Shot 2021-05-25 at 6 23 51 PM" src="https://user-images.githubusercontent.com/22921007/119588797-61dbe380-bd86-11eb-85ab-18561ad64672.png">

**Comment by hritikaggarwal2** [comment]
Hello there,
Thank you for raising this issue, we have added a bit more clarification and a workaround for this. You can head to [this](https://github.com/hritikaggarwal2/husky-buddy/blob/main/web/README.md#creating--using-your-own-firebase-project) section and find the necessary steps to setting up your own firebase.
