### ISSUE TITLE
Installing Node dependencies on macOS results in aborted operation

### ISSUE THREAD

**Issue by nlstrait** [hritikaggarwal2/husky-buddy#33]
At [this step in the instructions](https://github.com/hritikaggarwal2/husky-buddy/blob/main/web/README.md#installing-node-dependencies), running `npm install` results in...

<img width="570" alt="Screen Shot 2021-05-25 at 6 45 37 PM" src="https://user-images.githubusercontent.com/22921007/119590327-66ee6200-bd89-11eb-9351-46547a575da4.png">

**Comment by nlstrait** [comment]
It looks like it may be a macOS package management problem...

**Comment by nlstrait** [comment]
Following controversial instructions in [this StackOverflow post](https://stackoverflow.com/a/54873233/7466271) (commands shown below), I was able to get npm actually started in the installation process (whereas before it aborted immediately).

On macOS:
`brew upgrade`
`brew clean`

**Comment by hritikaggarwal2** [comment]
It appears that this happens because of an improper node installation. This is not something we can list in our documentation as it pertains to an incorrect node setup environment. But this is a great catch. Thank you for the update!

**Comment by nlstrait** [comment]
Like with the other issue, there is "something [you] can list in [your] documentation": node and npm! I was just lucky enough to have an old install, and I still barely know anything about either. Where should I get them? What versions are expected for this project? What environment are the Husky Buddy developers using? I don't appreciate your lazy answers after I gave such thorough feedback.
